### ISSUE TITLE
(R1 Beta) Issues/Suggestions on Belt Tensioning Mechanism

### ISSUE THREAD

**Issue by skuep** [PrintersForAnts/Micron#122]
- There was one minor issue with the motor mount, where there is an unprintable overhang. Probably something a chamfer can already fix.
![tensioner-2](https://github.com/PrintersForAnts/Micron/assets/5630293/9a7edf70-98ac-4d2c-9f17-356370101fe5)
![IMG_20240516_172949](https://github.com/PrintersForAnts/Micron/assets/5630293/8d956a4c-72ee-4409-b513-16990b9dd5cf)

- In my setup (152mm Belt, 16T pulley and 64T POWGE Pulley) this picture represents a pretty tight tensioned belt already. The M3x12 screw tensioning screw only grabs half a turn at this point. I needed to change it for a M3x16. Is this by design? I think this particular thing is also misaligned in the CAD.
![IMG_20240516_171114](https://github.com/PrintersForAnts/Micron/assets/5630293/8e33e97b-f480-4612-9a27-4bb0be6175a1)

- It might also be worthwhile, to widen the slot so that we can use a regular DIN125 size washer below those two fixation screws. Otherwise the slot gets mangled up pretty fast by those small screw heads.

- Is it possible to integrate a window into one of the sides of the mechanism to see if the motor pulley height is aligned correctly? Maybe even to better check the belt tension than by poking in an allen key from the top at an angle to see the belt tension. Maybe on the side facing downwards?

![IMG_20240516_161652](https://github.com/PrintersForAnts/Micron/assets/5630293/0af6ad86-364d-498f-b5c1-78a42e6eb4ce)

**Comment by hartk1213** [comment]
Issue 1 , heatset holes now chamfered
![image](https://github.com/PrintersForAnts/Micron/assets/12398294/4e5feb25-c2c7-4385-9c5d-86efda9bfe8c)

Issue 2a, slots now big enough to accept m3 washers 7mm OD, .5mm thick same washers used in other locations of the build 
![image](https://github.com/PrintersForAnts/Micron/assets/12398294/e629c905-b0e5-45dc-a602-0dc3fda668c9)

Issue 2b, yeah good call changing that screw to m3x16 instead of m3x12, there is plenty of room for a 16SHCS there 
![image](https://github.com/PrintersForAnts/Micron/assets/12398294/75070e4e-1281-4974-ba70-fc7c68998dea)

issue 3, added small window to check belt alignment 
![image](https://github.com/PrintersForAnts/Micron/assets/12398294/485f3d28-7ca2-4e6c-8afb-dc9d7711534d)


ill get these changes exported to and pushed to the repo then ill close the issue

**Comment by skuep** [comment]
Awesome, that looks really nice!
